[package]
name = "sync_application"
version = "0.0.0"
edition = "2021"

[dependencies]
config = {version = "0.13.3", default-features = false, features = ["json"]}
hex-literal = "0.4.1"
md-5 = "0.10.6"
serde = "1.0.189"
threadpool = "1.8.1"
walkdir = "2.4.0"
